[package]
name = "file-append-newline"
version = "0.1.0"
authors = ["Li Lei <this.lilei@gmail.com>"]
edition = "2021"

[dependencies]
toml = "0.5.8"
serde = { version = "1.0.136", features = ["derive"] }
once_cell = "1.10.0"
anyhow = "1.0.56"
