create table "user"
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    deleted_at timestamp,
    updated_at timestamp,
    name       varchar(255)
);
